spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/microservice  # URL of the MySQL server
    username: root                         # MySQL username
    password:
  jpa:
    hibernate:
      ddl-auto: update                     # Automatically create/validate tables (e.g., create, update, validate)
    show-sql: true                          # Show SQL statements in logs
    properties:
      hibernate:
        format_sql: true

  application:
    name: product-service
server:
  port: 9090

                 # MySQL password
#    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver
#    hikari:
#      pool-name: HikariCP                  # HikariCP connection pool (default pool in Spring Boot)
#      maximum-pool-size: 10                # Maximum number of connections in the pool
#      minimum-idle: 5                      # Minimum number of idle connections in the pool
#      idle-timeout: 30000                  # Maximum time a connection can be idle (in milliseconds)
#      connection-timeout: 30000            # Maximum time to wait for a connection from the pool (in milliseconds)
#      max-lifetime: 1800000                # Maximum lifetime of a connection (in milliseconds)
        # Format SQL for readability
